In [217]:
import tensorflow as tf
from tensorflow import keras
from keras.layers import Flatten, Dense
import numpy as np
from sklearn.model_selection import train_test_split

#### In the first level I defined a neural network model for the given task and I set 2 hidden layers with 50 neurons for each one, and I set the weights of these hidden layers using a kernel initializer with zero values then printed the weights of hidden layers.
#### I fitted the model and monitored the accuracy at each epoch and the accuracy remained unchanged during the training, showing no improvement over the epochs. After completion of training, I printed the weights of the hidden layers once again and  found that they were still set to zero.

#### The reason of this lack of weight changes in the hidden layers:  by setting wights of layers to zero in neural network , the gradient updates during the learning process become zero as well  and as the result weights don’t be updated after each epoch and accuracy and weights remains the same . In cases where there might be any changes in the values after training , they are very small and very close to zero.


In [198]:
(X_train, y_train), (X_test, y_test) = keras.datasets.cifar10.load_data()

In [199]:
X_train, X_test = X_train/255.0, X_test/255.0

In [211]:
model = keras.models.Sequential()
model.add(Flatten(input_shape=[32, 32, 3]))
model.add(Dense(50, activation='selu', kernel_initializer='zeros'))
model.add(Dense(50, activation='selu', kernel_initializer='zeros'))
model.add(Dense(10, activation='softmax'))

In [212]:
model.summary()

Model: "sequential_34"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_22 (Flatten)        (None, 3072)              0         
                                                                 
 dense_85 (Dense)            (None, 50)                153650    
                                                                 
 dense_86 (Dense)            (None, 50)                2550      
                                                                 
 dense_87 (Dense)            (None, 10)                510       
                                                                 
Total params: 156,710
Trainable params: 156,710
Non-trainable params: 0
_________________________________________________________________


In [213]:
model.compile(loss="sparse_categorical_crossentropy",
              optimizer='sgd',
              metrics=["accuracy"])

In [214]:
# Display the initial weights
print("Initial Weights:")
for i in range(1, len(model.layers)):
    weights = model.layers[i].get_weights()[0]
    print('weights in layers %d :'%i , '\n',weights)

Initial Weights:
weights in layers 1 : 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
weights in layers 2 : 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
weights in layers 3 : 
 [[ 0.10973138 -0.29080155  0.20979276  0.15508899  0.26701483 -0.01455259
  -0.07518053  0.07037285  0.08500731  0.23889253]
 [ 0.22059211  0.2220895   0.28648213 -0.29442093 -0.17442165 -0.2256102
   0.21362266  0.07035491 -0.28971678  0.310693  ]
 [-0.21696228 -0.17848392 -0.13951442 -0.06944451 -0.14128174 -0.0068965
   0.19599482  0.13682503 -0.064973    0.14033887]
 [ 0.03322631 -0.03104779  0.25720468 -0.25893655 -0.17637068 -0.29059225
  -0.12933713  0.08127904  0.24131796  0.26122352]
 [-0.2840137   0.27168414 -0.04420233 -0.29106942  0.2912096   0.29333863
   0.25912932  0.25949213  

In [215]:
model.fit(X_train, y_train, epochs=50 , validation_split=0.15)

Epoch 1/50
1329/1329 [==============================] - 3s 2ms/step - loss: 2.3029 - accuracy: 0.0994 - val_loss: 2.3030 - val_accuracy: 0.0975
Epoch 2/50
1329/1329 [==============================] - 3s 2ms/step - loss: 2.3029 - accuracy: 0.0975 - val_loss: 2.3029 - val_accuracy: 0.0975
Epoch 3/50
1329/1329 [==============================] - 2s 2ms/step - loss: 2.3028 - accuracy: 0.0995 - val_loss: 2.3025 - val_accuracy: 0.1029
Epoch 4/50
1329/1329 [==============================] - 3s 2ms/step - loss: 2.3027 - accuracy: 0.1005 - val_loss: 2.3031 - val_accuracy: 0.1000
Epoch 5/50
1329/1329 [==============================] - 3s 2ms/step - loss: 2.3029 - accuracy: 0.0985 - val_loss: 2.3028 - val_accuracy: 0.1000
Epoch 6/50
1329/1329 [==============================] - 3s 2ms/step - loss: 2.3028 - accuracy: 0.0990 - val_loss: 2.3032 - val_accuracy: 0.0984
Epoch 7/50
1329/1329 [==============================] - 3s 2ms/step - loss: 2.3029 - accuracy: 0.0996 - val_loss: 2.3027 - val_accuracy:

In [216]:
# Display the initial weights
print("Initial Weights after fitting:")
for i in range(1, len(model.layers)):
    weights = model.layers[i].get_weights()[0]
    print('weights in layers %d :'%i , '\n',weights)

Initial Weights after fitting:
weights in layers 1 : 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
weights in layers 2 : 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
weights in layers 3 : 
 [[ 0.109305   -0.28671145  0.208579    0.15420647  0.26440787 -0.0134424
  -0.07314669  0.07042203  0.08446556  0.23728739]
 [ 0.21802984  0.2204547   0.28364557 -0.2908506  -0.17204575 -0.2228315
   0.21301152  0.06895004 -0.285429    0.30672243]
 [-0.21475409 -0.17670375 -0.13842742 -0.06847437 -0.14040926 -0.00732858
   0.19375858  0.13469824 -0.06461022  0.13784909]
 [ 0.03202296 -0.03067698  0.2548189  -0.2559132  -0.17488205 -0.2869599
  -0.12699452  0.07950331  0.23858891  0.25845844]
 [-0.27964464  0.26929346 -0.0425675  -0.2858489   0.28888088  0.29184982
   0.25779486 